name: CI/CD

on:
  pull_request:
    branches:
      - main

# on:
#   push:
#     branches:
#       - main

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
      
      - name: Tag Release
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Login to Docker
        run: |
          docker images
          echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login --username rekram --password-stdin

      - name: Publish Docker Image
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }} 
